// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	BOT_SERVICE_URL: "https://weedge-achatbot--fastapi-webrtc-audio-bot-srv-app.modal.run/bot_join/DailyStoryTellingBot";
	BOT_SERVICE_AUTH: "";
}
