// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	BOT_SERVICE_URL: "http://localhost:4321/bot_join/DailyStoryTellingBot";
	BOT_SERVICE_AUTH: "";
}
